const express = require("express")
const router = express.Router()
const controller = require("../controllers/events.controller")
const auth = require("../middlewares/auth.middleware")
const proponentClearance = require("../middlewares/proponentClearance.middleware")

router.get("/", controller.get)
router.get("/dates/", controller.getOccasions)
router.get("/dates/:date", controller.getByDate)
router.get("/ids/:id", controller.getById)
router.get("/ids/:id/related", controller.getByIdAndRelated)
router.get("/enrollments/:id", controller.getEnrolledByUserId)
router.get("/authors/:id", controller.getByAuthorId)
router.post("/", /*auth, proponentClearance, */controller.add)
router.put("/:id", /*auth, proponentClearance, */controller.edit)
router.delete("/:id", /*auth, proponentClearance, */controller.remove)

module.exports = app => app.use("/events", router)